### ISSUE TITLE
【高级篇】自定义口令功能

### ISSUE THREAD

**Issue by hanxi** [hanxi/xiaomusic#105]
自定义口令配置需要配置到 config.json 文件里，使用 config.json 方式启动。参考 <https://github.com/hanxi/xiaomusic/issues/94> 。

口令的配置方式见 config-example.json 文件。口令对应的代码需要写到 `plugins/` 目录下面，如果是容器启动，则需要把这个目录挂载出来。

config.json 格式是下面这样的。

```json
{
    "hardware": "L07A",
    "account": "",
    "password": "",
    "mi_did": "",
    "cookie": "",
    "verbose": false,
    "music_path": "music",
    "conf_path": null,
    "hostname": "192.168.2.5",
    "port": 8090,
    "public_port": 0,
    "proxy": null,
    "search_prefix": "bilisearch:",
    "ffmpeg_location": "./ffmpeg/bin",
    "active_cmd": "play,random_play,playlocal,play_music_list,stop",
    "exclude_dirs": "@eaDir",
    "music_path_depth": 10,
    "disable_httpauth": true,
    "httpauth_username": "admin",
    "httpauth_password": "admin",
    "music_list_url": "",
    "music_list_json": "",
    "disable_download": false,
    "key_word_dict": {
        "播放歌曲": "play",
        "播放本地歌曲": "playlocal",
        "关机": "stop",
        "下一首": "play_next",
        "单曲循环": "set_play_type_one",
        "全部循环": "set_play_type_all",
        "随机播放": "random_play",
        "分钟后关机": "stop_after_minute",
        "播放列表": "play_music_list",
        "刷新列表": "gen_music_list",
        "set_volume#": "set_volume",
        "get_volume#": "get_volume",
        "本地播放歌曲": "playlocal",
        "放歌曲": "play",
        "暂停": "stop",
        "停止": "stop",
        "停止播放": "stop",
        "测试自定义口令": "exec#code1(\"hello\")",
        "测试链接": "exec#httpget(\"https://github.com/hanxi/xiaomusic\")"
    },
    "key_match_order": [
        "set_volume#",
        "get_volume#",
        "分钟后关机",
        "播放歌曲",
        "下一首",
        "单曲循环",
        "全部循环",
        "随机播放",
        "关机",
        "刷新列表",
        "播放列表",
        "播放本地歌曲",
        "本地播放歌曲",
        "放歌曲",
        "暂停",
        "停止",
        "停止播放",
        "测试自定义口令",
        "测试链接"
    ],
    "use_music_api": false,
    "use_music_audio_id": "1582971365183456177",
    "use_music_id": "355454500",
    "log_file": "/tmp/xiaomusic.txt",
    "fuzzy_match_cutoff": 0.6,
    "enable_fuzzy_match": true,
    "stop_tts_msg": "收到,再见",
    "keywords_playlocal": "播放本地歌曲,本地播放歌曲",
    "keywords_play": "播放歌曲,放歌曲",
    "keywords_stop": "关机,暂停,停止,停止播放",
    "user_key_word_dict": {
        "测试自定义口令": "exec#code1(\"hello\")",
        "测试链接": "exec#httpget(\"https://github.com/hanxi/xiaomusic\")"
    }
}
```

配置自定义口令时，只需要配置 user_key_word_dict 即可，会自动插入到 key_word_dict 里的。配置格式是：

```
 "测试自定义口令": "exec#code1(\"hello\")",
```

**Comment by carson512** [comment]
如果开启服务的状态下 如何唤醒才能调用原有的播放QQ 网易云？而特定唤醒词调用xiaoai播放？

**Comment by hanxi** [comment]
> 如果开启服务的状态下 如何唤醒才能调用原有的播放QQ 网易云？而特定唤醒词调用xiaoai播放？

不使用 xiaomusic 的唤醒词就会调用音箱自带的，比如说播放音乐

**Comment by shellingford37** [comment]
```
[23:26:12] [0.3.30] [INFO] xiaomusic.py:531: 收到消息:测试自定义口令 控制面板:False did:290874427
[23:26:12] [0.3.30] [INFO] xiaomusic.py:577: 完全匹配指令. query:测试自定义口令 opvalue:exec#code1("hello")
[23:26:12] [0.3.30] [INFO] code1.py:3: code1:hello
[23:26:12] [0.3.30] [ERROR] xiaomusic.py:542: Execption XiaoMusic.do_tts() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "/app/xiaomusic/xiaomusic.py", line 540, in do_check_cmd
    await func(did=did, arg1=oparg)
  File "/app/xiaomusic/xiaomusic.py", line 890, in exec
    await self.plugin_manager.execute_plugin(code)
  File "/app/xiaomusic/plugin.py", line 66, in execute_plugin
    await coroutine
  File "/app/plugins/code1.py", line 4, in code1
    await xiaomusic.do_tts("你好，我是自定义的测试口令")
TypeError: XiaoMusic.do_tts() missing 1 required positional argument: 'value'
```

我用code1的代码执行报错，有大佬知道为什么吗？

**Comment by hanxi** [comment]
接口修改了，忘记改这里了。

**Comment by hanxi** [comment]
@shellingford37 重构后漏改了，修复了。

**Comment by guoxiangke** [comment]
先说播放歌曲，再说 测试自定义口令 就行

**Comment by CZJCC** [comment]
想请教下插件那个功能，如何把用户的语音输入作为参数内容传到自定义函数里

**Comment by hanxi** [comment]
> 想请教下插件那个功能，如何把用户的语音输入作为参数内容传到自定义函数里

现在获取不到，等我加个接口获取吧。

**Comment by CZJCC** [comment]
666,支持以后我可以贡献一个接入通义模型的插件

**Comment by hanxi** [comment]
@CZJCC 你可以更新看看 plugins/code1.py 的测试代码，我测试了是可以拿到语音输入的原始内容的。

**Comment by CZJCC** [comment]
> @CZJCC 你可以更新看看 plugins/code1.py 的测试代码，我测试了是可以拿到语音输入的原始内容的。

我原先设想的事用户的话术是”通义提问为什么地球是圆的“，指令匹配的时候通义提问前缀匹配到类似于code1方法，为什么地球是圆的作为参数传入这个函数，但我看现在是拿历史记录实现的

**Comment by hanxi** [comment]
是的，插件函数里面再切割一下前缀就行。last_record就是当前的那条语音数据。

**Comment by hanxi** [comment]
> > @CZJCC 你可以更新看看 plugins/code1.py 的测试代码，我测试了是可以拿到语音输入的原始内容的。
> 
> 我原先设想的事用户的话术是”通义提问为什么地球是圆的“，指令匹配的时候通义提问前缀匹配到类似于code1方法，为什么地球是圆的作为参数传入这个函数，但我看现在是拿历史记录实现的

是的，这样比较简单，交给插件里面处理也比较自由。

**Comment by mogeqian** [comment]
key_word_dict中的“播放歌曲”口令是不能修改的是吧？因为以前用小爱同学播放歌曲说习惯了，总是触发xiaomusic自动下载歌曲，我想把口令改成“查找歌曲”，这样我当说播放歌曲的时候就调用网易云音乐或者QQ音乐，当我说查找歌曲的时候就先看本地有没有，没有就自动下载到本地，
"key_word_dict": {
        "播放歌曲": "play",

**Comment by mogeqian** [comment]
key_word_dict中的“播放歌曲”口令是不能修改的是吧？因为以前用小爱同学播放歌曲说习惯了，总是触发xiaomusic自动下载歌曲，我想把口令改成“查找歌曲”，这样我当说播放歌曲的时候就调用网易云音乐或者QQ音乐，当我说查找歌曲的时候就先看本地有没有歌曲，没有话就自动下载到本地。
当我先按照config-example.json的模板写好如下配置并重命名为config.json
```
  "key_word_dict": {
    "查找歌曲": "play",
    "播放本地歌曲": "playlocal",
    "关机": "stop",
    "下一首": "play_next",
    "单曲循环": "set_play_type_one",
    "全部循环": "set_play_type_all",
    "随机播放": "set_random_play",
    "分钟后关机": "stop_after_minute",
    "播放列表": "play_music_list",
    "刷新列表": "gen_music_list",
    "本地播放歌曲": "playlocal",
    "下载歌曲": "play",
    "暂停": "stop",
    "停止": "stop",
    "停止播放": "stop",
    "测试自定义口令": "exec#code1(\"hello\")",
    "测试链接": "exec#httpget(\"https://github.com/hanxi/xiaomusic\")"
  },
  "key_match_order": [
    "分钟后关机",
    "查找歌曲",
    "下一首",
    "单曲循环",
    "全部循环",
    "随机播放",
    "关机",
    "刷新列表",
    "播放列表",
    "播放本地歌曲",
    "本地播放歌曲",
    "下载歌曲",
    "暂停",
    "停止",
    "停止播放",
    "测试自定义口令",
    "测试链接"
  ],
```

用以下命令安装docker
`docker run --name xiaomusic -p 5488:5488 -v /mnt/sharedata/audiodata/musci/xiaomusic:/app/music -v /mnt/data_sdb1/docker/xiaomusic/config.json:/app/config.json -e XIAOMUSIC_PORT=5488 hanxi/xiaomusic --config /app/config.json`
日志里提示的依然是：

 key_word_dict={'播放歌曲': 'play', '播放本地歌曲': 'playlocal', '关机': 'stop', '下一首': 'play_next', '上一首': 'play_prev', '单曲循环': 'set_play_type_one', '全部循环': 'set_play_type_all', '随机播放': 'set_random_play', '分钟后关机': 'stop_after_minute', '播放列表': 'play_music_list', '刷新列表': 'gen_music_list', '加入收藏': 'add_to_favorites', '收藏歌曲': 'add_to_favorites', '取消收藏': 'del_from_favorites', '播放列表第': 'play_music_list_index', '本地播放歌曲': 'playlocal', '查找歌曲': 'play', '下载歌曲': 'play', '暂停': 'stop', '停止': 'stop', '停止播放': 'stop', '播放歌单': 'play_music_list', '测试自定义口令': 'exec#code1("hello")', '测试链接': 'exec#httpget("https://github.com/hanxi/xiaomusic")'}, key_match_order=['分钟后关机', '播放歌曲', '下一首', '上一首', '单曲循环', '全部循环', '随机播放', '关机', '刷新列表', '播放列表第', '播放列表', '加入收藏', '收藏歌曲', '取消收藏', '播放本地歌曲', '本地播放歌曲', '查找歌曲', '下载歌曲', '暂停', '停止', '停止播放', '播放歌单', '测试自定义口令', '测试链接']

似乎自定义的口令只能以插入的方式添加上去，并不能替换掉原来的口令

**Comment by hanxi** [comment]
> key_word_dict中的“播放歌曲”口令是不能修改的是吧？因为以前用小爱同学播放歌曲说习惯了，总是触发xiaomusic自动下载歌曲，我想把口令改成“查找歌曲”，这样我当说播放歌曲的时候就调用网易云音乐或者QQ音乐，当我说查找歌曲的时候就先看本地有没有歌曲，没有话就自动下载到本地。 当我先按照config-example.json的模板写好如下配置并重命名为config.json
> 
> ```
>   "key_word_dict": {
>     "查找歌曲": "play",
>     "播放本地歌曲": "playlocal",
>     "关机": "stop",
>     "下一首": "play_next",
>     "单曲循环": "set_play_type_one",
>     "全部循环": "set_play_type_all",
>     "随机播放": "set_random_play",
>     "分钟后关机": "stop_after_minute",
>     "播放列表": "play_music_list",
>     "刷新列表": "gen_music_list",
>     "本地播放歌曲": "playlocal",
>     "下载歌曲": "play",
>     "暂停": "stop",
>     "停止": "stop",
>     "停止播放": "stop",
>     "测试自定义口令": "exec#code1(\"hello\")",
>     "测试链接": "exec#httpget(\"https://github.com/hanxi/xiaomusic\")"
>   },
>   "key_match_order": [
>     "分钟后关机",
>     "查找歌曲",
>     "下一首",
>     "单曲循环",
>     "全部循环",
>     "随机播放",
>     "关机",
>     "刷新列表",
>     "播放列表",
>     "播放本地歌曲",
>     "本地播放歌曲",
>     "下载歌曲",
>     "暂停",
>     "停止",
>     "停止播放",
>     "测试自定义口令",
>     "测试链接"
>   ],
> ```
> 
> 用以下命令安装docker `docker run --name xiaomusic -p 5488:5488 -v /mnt/sharedata/audiodata/musci/xiaomusic:/app/music -v /mnt/data_sdb1/docker/xiaomusic/config.json:/app/config.json -e XIAOMUSIC_PORT=5488 hanxi/xiaomusic --config /app/config.json` 日志里提示的依然是：
> 
> ` key_word_dict={'播放歌曲': 'play', '播放本地歌曲': 'playlocal', '关机': 'stop', '下一首': 'play_next', '上一首': 'play_prev', '单曲循环': 'set_play_type_one', '全部循环': 'set_play_type_all', '随机播放': 'set_random_play', '分钟后关机': 'stop_after_minute', '播放列表': 'play_music_list', '刷新列表': 'gen_music_list', '加入收藏': 'add_to_favorites', '收藏歌曲': 'add_to_favorites', '取消收藏': 'del_from_favorites', '播放列表第': 'play_music_list_index', '本地播放歌曲': 'playlocal', '查找歌曲': 'play', '下载歌曲': 'play', '暂停': 'stop', '停止': 'stop', '停止播放': 'stop', '播放歌单': 'play_music_list', '测试自定义口令': 'exec#code1("hello")', '测试链接': 'exec#httpget("https://github.com/hanxi/xiaomusic")'}, key_match_order=['分钟后关机', '播放歌曲', '下一首', '上一首', '单曲循环', '全部循环', '随机播放', '关机', '刷新列表', '播放列表第', '播放列表', '加入收藏', '收藏歌曲', '取消收藏', '播放本地歌曲', '本地播放歌曲', '查找歌曲', '下载歌曲', '暂停', '停止', '停止播放', '播放歌单', '测试自定义口令', '测试链接']`
> 
> 似乎自定义的口令只能以插入的方式添加上去，并不能替换掉原来的口令

可以在网页后台设置页面改。

**Comment by mogeqian** [comment]
不行，后台设置如图
![QQ截图20241111181411](https://github.com/user-attachments/assets/cc89512f-cab9-488d-b0d6-5b2a3a720ac2)
日志如下：
```
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:1130: update_config_from_setting ok. data:Config(account='**', password='**', mi_did='726577518,570867755', miio_tts_command='', cookie='', verbose=False, music_path='music', download_path='music/download', conf_path='conf', cache_dir='cache', hostname='192.168.22.4', port=8090, public_port=0, proxy='', search_prefix='bilisearch:', ffmpeg_location='./ffmpeg/bin', active_cmd='play,set_random_play,playlocal,play_music_list,stop', exclude_dirs='@eaDir', music_path_depth=10, disable_httpauth=True, httpauth_username='******', httpauth_password='******', music_list_url='', music_list_json='', custom_play_list_json='', disable_download=False, key_word_dict={'播放歌曲': 'play', '播放本地歌曲': 'playlocal', '关机': 'stop', '下一首': 'play_next', '上一首': 'play_prev', '单曲循环': 'set_play_type_one', '全部循环': 'set_play_type_all', '随机播放': 'set_random_play', '分钟后关机': 'stop_after_minute', '播放列表': 'play_music_list', '刷新列表': 'gen_music_list', '加入收藏': 'add_to_favorites', '收藏歌曲': 'add_to_favorites', '取消收藏': 'del_from_favorites', '播放列表第': 'play_music_list_index', '本地播放歌曲': 'playlocal', '查找歌曲': 'play', '下载歌曲': 'play', '暂停': 'stop', '停止': 'stop', '停止播放': 'stop', '播放歌单': 'play_music_list', '测试自定义口令': 'exec#code1("hello")', '测试链接': 'exec#httpget("https://github.com/hanxi/xiaomusic")'}, key_match_order=['分钟后关机', '播放歌曲', '下一首', '上一首', '单曲循环', '全部循环', '随机播放', '关机', '刷新列表', '播放列表第', '播放列表', '加入收藏', '收藏歌曲', '取消收藏', '播放本地歌曲', '本地播放歌曲', '查找歌曲', '下载歌曲', '暂停', '停止', '停止播放', '播放歌单', '测试自定义口令', '测试链接'], use_music_api=False, use_music_audio_id='1582971365183456177', use_music_id='355454500', log_file='/tmp/xiaomusic.txt', fuzzy_match_cutoff=0.6, enable_fuzzy_match=True, stop_tts_msg='收到,再见', enable_config_example=False, keywords_playlocal='播放本地歌曲,本地播放歌曲', keywords_play='查找歌曲,下载歌曲', keywords_stop='关机,暂停,停止,停止播放', keywords_playlist='播放列表,播放歌单', user_key_word_dict={'测试自定义口令': 'exec#code1("hello")', '测试链接': 'exec#httpget("https://github.com/hanxi/xiaomusic")'}, enable_force_stop=False, devices={'726577518': Device(did='726577518', device_id='******', hardware='LX06', name='小爱音箱Pro', play_type='', cur_music='', cur_playlist='全部'), '570867755': Device(did='570867755', device_id='*********', hardware='L15A', name='小米AI音箱(第二代)', play_type='', cur_music='', cur_playlist='全部')}, group_list='', remove_id3tag=False, convert_to_mp3=False, delay_sec=3, continue_play=False, pull_ask_sec=1, crontab_json='', enable_yt_dlp_cookies=False, get_ask_by_mina=False)
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:1133: 语音控制已启动, 用【分钟后关机/播放歌曲/下一首/上一首/单曲循环/全部循环/随机播放/关机/刷新列表/播放列表第/播放列表/加入收藏/收藏歌曲/取消收藏/播放本地歌曲/本地播放歌曲/查找歌曲/下载歌曲/暂停/停止/停止播放/播放歌单/测试自定义口令/测试链接】开头来控制
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:543: 协程时间循环未启动
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:1250: 没打乱 全部 ['乌兰托娅 火红的萨日朗', '凤凰传奇麝香夫人'] ... ['罗大佑童年', '阿嬷'] with len: 7
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:1250: 没打乱 全部 ['乌兰托娅 火红的萨日朗', '凤凰传奇麝香夫人'] ... ['罗大佑童年', '阿嬷'] with len: 7
[2024-11-11 18:08:04] [0.3.46] [INFO] analytics.py:28: analytics init ok
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:104: Startup OK. Config(account='***', password='***', mi_did='726577518,570867755', miio_tts_command='', cookie='', verbose=False, music_path='music', download_path='music/download', conf_path='conf', cache_dir='cache', hostname='192.168.22.4', port=8090, public_port=0, proxy='', search_prefix='bilisearch:', ffmpeg_location='./ffmpeg/bin', active_cmd='play,set_random_play,playlocal,play_music_list,stop', exclude_dirs='@eaDir', music_path_depth=10, disable_httpauth=True, httpauth_username='******', httpauth_password='******', music_list_url='', music_list_json='', custom_play_list_json='', disable_download=False, key_word_dict={'播放歌曲': 'play', '播放本地歌曲': 'playlocal', '关机': 'stop', '下一首': 'play_next', '上一首': 'play_prev', '单曲循环': 'set_play_type_one', '全部循环': 'set_play_type_all', '随机播放': 'set_random_play', '分钟后关机': 'stop_after_minute', '播放列表': 'play_music_list', '刷新列表': 'gen_music_list', '加入收藏': 'add_to_favorites', '收藏歌曲': 'add_to_favorites', '取消收藏': 'del_from_favorites', '播放列表第': 'play_music_list_index', '本地播放歌曲': 'playlocal', '查找歌曲': 'play', '下载歌曲': 'play', '暂停': 'stop', '停止': 'stop', '停止播放': 'stop', '播放歌单': 'play_music_list', '测试自定义口令': 'exec#code1("hello")', '测试链接': 'exec#httpget("https://github.com/hanxi/xiaomusic")'}, key_match_order=['分钟后关机', '播放歌曲', '下一首', '上一首', '单曲循环', '全部循环', '随机播放', '关机', '刷新列表', '播放列表第', '播放列表', '加入收藏', '收藏歌曲', '取消收藏', '播放本地歌曲', '本地播放歌曲', '查找歌曲', '下载歌曲', '暂停', '停止', '停止播放', '播放歌单', '测试自定义口令', '测试链接'], use_music_api=False, use_music_audio_id='1582971365183456177', use_music_id='355454500', log_file='/tmp/xiaomusic.txt', fuzzy_match_cutoff=0.6, enable_fuzzy_match=True, stop_tts_msg='收到,再见', enable_config_example=False, keywords_playlocal='播放本地歌曲,本地播放歌曲', keywords_play='查找歌曲,下载歌曲', keywords_stop='关机,暂停,停止,停止播放', keywords_playlist='播放列表,播放歌单', user_key_word_dict={'测试自定义口令': 'exec#code1("hello")', '测试链接': 'exec#httpget("https://github.com/hanxi/xiaomusic")'}, enable_force_stop=False, devices={'726577518': Device(did='726577518', device_id='*****', hardware='LX06', name='小爱音箱Pro', play_type='', cur_music='', cur_playlist='全部'), '570867755': Device(did='570867755', device_id='*********', hardware='L15A', name='小米AI音箱(第二代)', play_type='', cur_music='', cur_playlist='全部')}, group_list='', remove_id3tag=False, convert_to_mp3=False, delay_sec=3, continue_play=False, pull_ask_sec=1, crontab_json='', enable_yt_dlp_cookies=False, get_ask_by_mina=False)
[2024-11-11 18:08:04] [0.3.46] [INFO] httpserver.py:111: disable_httpauth:True
[18:08:04] [0.3.46] [INFO] Started server process [1]
[18:08:04] [0.3.46] [INFO] Waiting for application startup.
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:541: 启动后台构建 tag cache
[18:08:04] [0.3.46] [INFO] Application startup complete.
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:513: 已从【cache/tag_cache.json】加载 tag cache
[18:08:04] [0.3.46] [INFO] Uvicorn running on http://['0.0.0.0', '::']:8090 (Press CTRL+C to quit)
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:527: 保存：tag cache 已保存到【cache/tag_cache.json】
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:577: tag 更新完成
[2024-11-11 18:08:04] [0.3.46] [INFO] xiaomusic.py:248: 选中的设备: {'726577518': Device(did='726577518', device_id='******', hardware='LX06', name='小爱音箱Pro', play_type='', cur_music='', cur_playlist='全部'), '570867755': Device(did='570867755', device_id='*********', hardware='L15A', name='小米AI音箱(第二代)', play_type='', cur_music='', cur_playlist='全部')}
[18:08:34] [0.3.46] [INFO] 172.20.0.1:35058 - "GET /static/default/setting.html HTTP/1.1" 304
[18:08:34] [0.3.46] [INFO] 172.20.0.1:35058 - "GET /getversion HTTP/1.1" 200
```
使用的docker-compose命令安装
services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /mnt/sharedata/audiodata/musci/xiaomusic:/app/music
      - /mnt/data_sdb1/docker/xiaomusic/config.json:/app/config.json
    command: ['--config', '/app/config.json']

根据日志的提示，'播放歌曲': 'play'依然存在，只是增加了 '查找歌曲': 'play', '下载歌曲': 'play', 这两个关于play的自定义口令，所以实际上play有三条口令 “播放歌曲、查找歌曲、下载歌曲”，能否删除掉'播放歌曲': 'play'这个系统默认的口令？只使用 '查找歌曲': 'play', '下载歌曲': 'play', 这两个关于play的自定义口令

**Comment by hanxi** [comment]
@mogeqian 另外提个 issue 吧，现在应该是不支持删除默认的口令。

**Comment by mogeqian** [comment]
好的，已经重开了一个issue  #259

**Comment by wjcroom** [comment]
"active_cmd": "play,set_random_play,playlocal,play_music_list,play_music_list_index,stop_after_minute,stop,测试自定义口令",
这个激活cmd是什么作用呢, 怎么看着默认的是函数,只有最后一个是中文呢? 
 
已经把自定义3thplay音量加入了. 其他的大点声小点声, 大点音,小点音.,还有好多.

**Comment by hanxi** [comment]
激活cmd支持配置 key 和 value，用于决定是否能在 xiaomusic 不播放的时候能否唤醒 xiaomusic 。

config.json 是基本废弃了，作为一个初始化配置存在。

暂停不方便做，没有好的接口控制音箱暂停，所以就没加这个口令。

**Comment by wjcroom** [comment]
> 激活cmd支持配置 key 和 value，用于决定是否能在 xiaomusic 不播放的时候能否唤醒 xiaomusic 。
> 
> config.json 是基本废弃了，作为一个初始化配置存在。
> 
> 暂停不方便做，没有好的接口控制音箱暂停，所以就没加这个口令。
1.现在有了停止，我觉得继续可以是重启最近一首歌，在停止前把正在播放存放在某处。存  stop 里的name可以吗。感觉会有重名呢？

2. 有没有可能让小爱在技能中心增加自己的【小音乐】技能，进入xiaomusic对话模式，直到退出。这样不再互相干扰。

**Comment by hanxi** [comment]
1. 目前会记录最后一次播放的歌曲，正常说播放歌曲，不带歌曲名字应该就会重头播放的。
2. 对话模式有些设备不支持，实现也比较复杂，xiaogpt那些项目是支持对话模式的，我就懒得支持了。

**Comment by thefreezoo** [comment]
我想写个可以读小说的，现在就是可以读不能关闭了，只能一次读完，我本想重新发送一条关闭命令，上一个自定义命令没有结束，似乎不能接受新的命令，包括关机，有什么语音控制接口可以关闭这个运行中的任务吗

**Comment by hanxi** [comment]
> 我想写个可以读小说的，现在就是可以读不能关闭了，只能一次读完，我本想重新发送一条关闭命令，上一个自定义命令没有结束，似乎不能接受新的命令，包括关机，有什么语音控制接口可以关闭这个运行中的任务吗

可以看看你是怎么写的？估计得用 asyncio 异步的写法。

**Comment by thefreezoo** [comment]
> > 我想写个可以读小说的，现在就是可以读不能关闭了，只能一次读完，我本想重新发送一条关闭命令，上一个自定义命令没有结束，似乎不能接受新的命令，包括关机，有什么语音控制接口可以关闭这个运行中的任务吗
> 
> 可以看看你是怎么写的？估计得用 asyncio 异步的写法。

python我用的不很熟，基本逻辑都是用服务器实现的，好像python不能直接这样开启异步线程：import json
import threading
import requests
import asyncio

async def getbook(xiaomusic):
    # global log, xiaomusic
    offset = '0'
    did = xiaomusic._cur_did
    
    requests.get("http://192.168.1.16:8001/note/off?off=N",timeout=100)
    while True:
        url="http://192.168.1.16:8001/note/list?name=test&offset=" + offset
        try:
            response=requests.get(url,timeout=100)
            if response.status_code==200:
                print(response.text)
                res = json.loads(response.text)
                await xiaomusic.do_tts(did, res['data'])
                offset=str(res["offset"])
                if res['off'] == 1:
                    break
            else:
                print(f"no 200")
                break
        except requests.exceptions.RequestException as e:
            print(f"{e}")
            break

def read():
    global log, xiaomusic
    loop=asyncio.get_event_loop()
    loop.run_until_complete(getbook(xiaomusic))

**Comment by hanxi** [comment]
@thefreezoo 你用了个死循环，把整个服务卡住了。你可以在死循环里加个 asyncio.sleep ，然后再写一个自定义口令杀掉你的这个 task 。

**Comment by thefreezoo** [comment]
> [@thefreezoo](https://github.com/thefreezoo) 你用了个死循环，把整个服务卡住了。你可以在死循环里加个 asyncio.sleep ，然后再写一个自定义口令杀掉你的这个 task 。
似乎还是不行，不能识别其他口令
import json
import threading
import requests
import asyncio

async def read():
    global log, xiaomusic
    offset = '0'
    did = xiaomusic._cur_did
    
    requests.get("http://192.168.1.16:8001/note/off?off=N",timeout=100)
    while True:
        url="http://192.168.1.16:8001/note/list?name=test&offset=" + offset
        try:
            response=requests.get(url,timeout=100)
            if response.status_code==200:
                print(response.text)
                res = json.loads(response.text)
                await xiaomusic.do_tts(did, res['data'])
                offset=str(res["offset"])
                if res['off'] == 1:
                    break
            else:
                print(f"no 200")
                break
        except requests.exceptions.RequestException as e:
            print(f"{e}")
            break
        await asyncio.sleep(1)

**Comment by hanxi** [comment]
要不你问问ai吧，你缺少一个自定义指令干掉你这个死循环。

**Comment by thefreezoo** [comment]
> 要不你问问ai吧，你缺少一个自定义指令干掉你这个死循环。

插件是同步调用的，需要把插件包装成任务放回当前事件循环，我把plugins.py异步调用那里直接改成在事件循环中执行，然后放回running_task，stop的时候在终止任务,这样就可以用关机命令了

**Comment by hu847266** [comment]
能不能实现播放玩一个歌曲自动暂停

**Comment by hanxi** [comment]
> 能不能实现播放玩一个歌曲自动暂停

设置为单曲播放模式就行。

**Comment by hu847266** [comment]
问一下这个如果设置了离家后停止播放音乐，改了这个还能实现吗

**Comment by hu847266** [comment]
用服务器配置，容器端口和ip填什么，ip填公网ip吗
