### ISSUE TITLE
保存失败，就添加了三项  账号、密码、ip

### ISSUE THREAD

**Issue by guiwushaonian** [hanxi/xiaomusic#111]
[07:35:20] [0.1.93] [ERROR] Exception on /savesetting [POST]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/.venv/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/asgiref/sync.py", line 250, in __call__
    loop_future = loop_executor.submit(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

型号：L05B

**Comment by guiwushaonian** [comment]
docker 拉取的版本还是 [0.1.93]，是版本的原因？

**Comment by hanxi** [comment]
这个报错是旧版本的问题，请更新后试试。

**Comment by guiwushaonian** [comment]
> 这个报错是旧版本的问题，请更新后试试。

更新版本后，正常播放  型号：L05B 版本：[0.1.101]
