### ISSUE TITLE
是必须用python3.10才行吗？

### ISSUE THREAD

**Issue by ansemz** [hanxi/xiaomusic#13]
我这个nas刚好只有3.7和3.11。3.7太老了，依赖直接装不了。
3.11可以装，不过一运行就报错。
nas还装不了docker，也无法编译安装python3.10。

```shell
Traceback (most recent call last):
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 905, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/client_proto.py", line 213, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/http_parser.py", line 661, in feed_data
    return super().feed_data(data, SEP, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/http_parser.py", line 339, in feed_data
    msg: _MsgT = self.parse_message(self._lines)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/http_parser.py", line 688, in parse_message
    raise BadStatusLine(line)
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line 'HTTP/1.1 200 '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/volume1/home/admin/xiaoai/xiaomusic/xiaomusic.py", line 5, in <module>
    main()
  File "/volume1/home/admin/xiaoai/xiaomusic/xiaomusic/cli.py", line 62, in main
    loop.run_until_complete(xiaomusic.run_forever())
  File "/opt/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
  File "/volume1/home/admin/xiaoai/xiaomusic/xiaomusic/xiaomusic.py", line 387, in run_forever
    await self.init_all_data(session)
  File "/volume1/home/admin/xiaoai/xiaomusic/xiaomusic/xiaomusic.py", line 95, in init_all_data
    await self._init_data_hardware()
  File "/volume1/home/admin/xiaoai/xiaomusic/xiaomusic/xiaomusic.py", line 115, in _init_data_hardware
    hardware_data = await self.mina_service.device_list()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/miservice/minaservice.py", line 27, in device_list
    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/miservice/miaccount.py", line 131, in mi_request
    async with self.session.request(
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/client.py", line 586, in _request
    await resp.start(conn)
  File "/volume1/home/admin/venvs/xiaomi-py311/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 907, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message="Bad status line 'HTTP/1.1 200 '", url=URL('https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_209R5SJmUgjfOrogY7cClAkPFLxu3X')
```

**Comment by hanxi** [comment]
你先尝试更新下依赖库的版本。用pdm工具升级一下依赖库。

**Comment by ansemz** [comment]
升级以后可以了，谢谢。
```shell
🔒 Lock successful
Synchronizing working set with resolved packages: 0 to add, 5 to update, 0 to remove

  ✔ Update miservice-fork 2.2.1 -> 2.3.2 successful
  ✔ Update websockets 11.0.3 -> 12.0 successful
  ✔ Update rich 13.6.0 -> 13.7.0 successful
  ✔ Update aiohttp 3.8.6 -> 3.9.3 successful
  ✔ Update yt-dlp 2023.10.13 -> 2023.12.30 successful
Installing the project as an editable package...
  ✔ Install xiaomusic 0.1.12 successful

🎉 All complete!
···
