### ISSUE TITLE
升级到0.3.12后出现错误：ModuleNotFoundError: No module named 'uvicorn'

### ISSUE THREAD

**Issue by Jackie264** [hanxi/xiaomusic#133]
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 4, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

**Comment by hanxi** [comment]
v0.3.13 修复。

**Comment by Jackie264** [comment]
这效率简直神了👍
