### ISSUE TITLE
之前都是好好的  突然所有的歌都播放不了 附上日志

### ISSUE THREAD

**Issue by lh0602** [hanxi/xiaomusic#145]
[xiaomusic.txt](https://github.com/user-attachments/files/16836337/xiaomusic.txt)
之前都是好好的 不知道啥情况 突然所有的歌都播放不了了 附上日志

[18:33:26] [0.3.27] [INFO] xiaomusic.py:1220: group_force_stop_xiaoai ['b0f386b4-d47a-4d67-83b3-f82b2a708b9b']
[18:33:26] [0.3.27] [ERROR] xiaomusic.py:987: Execption Error https://api2.mina.mi.com/remote/ubus: {'code': 100, 'message': 'ubus server internal error', 'data': {'msg': {'cause': None, 'stackTrace': [{'methodName': 'lambda$secureRelayV2$9', 'fileName': 'UbusSecurityUtils.java', 'lineNumber': 447, 'className': 'com.xiaomi.mico.common.util.UbusSecurityUtils', 'nativeMethod': False}, {'methodName': 'onSuccess', 'fileName': 'CallbackFuture.java', 'lineNumber': 34, 'className': 'com.facebook.swift.service.CallbackFuture$1', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Futures.java', 'lineNumber': 1132, 'className': 'com.google.common.util.concurrent.Futures$4', 'nativeMethod': False}, {'methodName': 'executeListener', 'fileName': 'AbstractFuture.java', 'lineNumber': 900, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'complete', 'fileName': 'AbstractFuture.java', 'lineNumber': 811, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'AbstractFuture.java', 'lineNumber': 653, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'CallbackFuture.java', 'lineNumber': 23, 'className': 'com.facebook.swift.service.CallbackFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 401, 'className': 'com.facebook.swift.service.ThriftMethodHandler$AsyncMethodCallFuture', 'nativeMethod': False}, {'methodName': 'onResponseReceived', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 244, 'className': 'com.facebook.swift.service.ThriftMethodHandler$1', 'nativeMethod': False}, {'methodName': 'fireResponseReceivedCallback', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 400, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'access$200', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 45, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 346, 'className': 'com.facebook.nifty.client.AbstractClientChannel$3', 'nativeMethod': False}, {'methodName': 'runWorker', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 1149, 'className': 'java.util.concurrent.ThreadPoolExecutor', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 624, 'className': 'java.util.concurrent.ThreadPoolExecutor$Worker', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Thread.java', 'lineNumber': 853, 'className': 'java.lang.Thread', 'nativeMethod': False}, {'methodName': 'runOutsideWisp', 'fileName': 'WispTask.java', 'lineNumber': 299, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'runCommand', 'fileName': 'WispTask.java', 'lineNumber': 274, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'access$100', 'fileName': 'WispTask.java', 'lineNumber': 53, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'WispTask.java', 'lineNumber': 241, 'className': 'com.alibaba.wisp.engine.WispTask$CacheableCoroutine', 'nativeMethod': False}, {'methodName': 'startInternal', 'fileName': 'CoroutineBase.java', 'lineNumber': 62, 'className': 'java.dyn.CoroutineBase', 'nativeMethod': False}], 'message': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 50026627,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'localizedMessage': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 50026627,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'suppressed': []}, 'reqID': 'app_ios_rpB02lxD3H4U1iPFenQJNvLIgh9MYO'}}
Traceback (most recent call last):
  File "/app/xiaomusic/xiaomusic.py", line 981, in force_stop_xiaoai
    ret = await self.xiaomusic.mina_service.player_pause(device_id)
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 79, in player_pause
    return await self.ubus_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 59, in ubus_request
    result = await self.mina_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 49, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 100, 'message': 'ubus server internal error', 'data': {'msg': {'cause': None, 'stackTrace': [{'methodName': 'lambda$secureRelayV2$9', 'fileName': 'UbusSecurityUtils.java', 'lineNumber': 447, 'className': 'com.xiaomi.mico.common.util.UbusSecurityUtils', 'nativeMethod': False}, {'methodName': 'onSuccess', 'fileName': 'CallbackFuture.java', 'lineNumber': 34, 'className': 'com.facebook.swift.service.CallbackFuture$1', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Futures.java', 'lineNumber': 1132, 'className': 'com.google.common.util.concurrent.Futures$4', 'nativeMethod': False}, {'methodName': 'executeListener', 'fileName': 'AbstractFuture.java', 'lineNumber': 900, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'complete', 'fileName': 'AbstractFuture.java', 'lineNumber': 811, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'AbstractFuture.java', 'lineNumber': 653, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'CallbackFuture.java', 'lineNumber': 23, 'className': 'com.facebook.swift.service.CallbackFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 401, 'className': 'com.facebook.swift.service.ThriftMethodHandler$AsyncMethodCallFuture', 'nativeMethod': False}, {'methodName': 'onResponseReceived', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 244, 'className': 'com.facebook.swift.service.ThriftMethodHandler$1', 'nativeMethod': False}, {'methodName': 'fireResponseReceivedCallback', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 400, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'access$200', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 45, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 346, 'className': 'com.facebook.nifty.client.AbstractClientChannel$3', 'nativeMethod': False}, {'methodName': 'runWorker', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 1149, 'className': 'java.util.concurrent.ThreadPoolExecutor', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 624, 'className': 'java.util.concurrent.ThreadPoolExecutor$Worker', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Thread.java', 'lineNumber': 853, 'className': 'java.lang.Thread', 'nativeMethod': False}, {'methodName': 'runOutsideWisp', 'fileName': 'WispTask.java', 'lineNumber': 299, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'runCommand', 'fileName': 'WispTask.java', 'lineNumber': 274, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'access$100', 'fileName': 'WispTask.java', 'lineNumber': 53, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'WispTask.java', 'lineNumber': 241, 'className': 'com.alibaba.wisp.engine.WispTask$CacheableCoroutine', 'nativeMethod': False}, {'methodName': 'startInternal', 'fileName': 'CoroutineBase.java', 'lineNumber': 62, 'className': 'java.dyn.CoroutineBase', 'nativeMethod': False}], 'message': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 50026627,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'localizedMessage': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 50026627,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'suppressed': []}, 'reqID': 'app_ios_rpB02lxD3H4U1iPFenQJNvLIgh9MYO'}}
[18:33:26] [0.3.27] [INFO] xiaomusic.py:1223: group_force_stop_xiaoai ['b0f386b4-d47a-4d67-83b3-f82b2a708b9b'] [None]
[18:33:26] [0.3.27] [INFO] xiaomusic.py:946: 播放 http://192.168.0.101:8090/music/download/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E8%8B%B1%E6%96%87%E6%AD%8CTOP100/Lou%20Bega%20-%20Angelina.wav
[18:33:26] [0.3.27] [ERROR] xiaomusic.py:1156: Execption Error https://api2.mina.mi.com/remote/ubus: {'code': 100, 'message': 'ubus server internal error', 'data': {'msg': {'cause': None, 'stackTrace': [{'methodName': 'lambda$secureRelayV2$9', 'fileName': 'UbusSecurityUtils.java', 'lineNumber': 447, 'className': 'com.xiaomi.mico.common.util.UbusSecurityUtils', 'nativeMethod': False}, {'methodName': 'onSuccess', 'fileName': 'CallbackFuture.java', 'lineNumber': 34, 'className': 'com.facebook.swift.service.CallbackFuture$1', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Futures.java', 'lineNumber': 1132, 'className': 'com.google.common.util.concurrent.Futures$4', 'nativeMethod': False}, {'methodName': 'executeListener', 'fileName': 'AbstractFuture.java', 'lineNumber': 900, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'complete', 'fileName': 'AbstractFuture.java', 'lineNumber': 811, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'AbstractFuture.java', 'lineNumber': 653, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'CallbackFuture.java', 'lineNumber': 23, 'className': 'com.facebook.swift.service.CallbackFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 401, 'className': 'com.facebook.swift.service.ThriftMethodHandler$AsyncMethodCallFuture', 'nativeMethod': False}, {'methodName': 'onResponseReceived', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 244, 'className': 'com.facebook.swift.service.ThriftMethodHandler$1', 'nativeMethod': False}, {'methodName': 'fireResponseReceivedCallback', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 400, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'access$200', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 45, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 346, 'className': 'com.facebook.nifty.client.AbstractClientChannel$3', 'nativeMethod': False}, {'methodName': 'runWorker', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 1149, 'className': 'java.util.concurrent.ThreadPoolExecutor', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 624, 'className': 'java.util.concurrent.ThreadPoolExecutor$Worker', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Thread.java', 'lineNumber': 853, 'className': 'java.lang.Thread', 'nativeMethod': False}, {'methodName': 'runOutsideWisp', 'fileName': 'WispTask.java', 'lineNumber': 299, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'runCommand', 'fileName': 'WispTask.java', 'lineNumber': 274, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'access$100', 'fileName': 'WispTask.java', 'lineNumber': 53, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'WispTask.java', 'lineNumber': 241, 'className': 'com.alibaba.wisp.engine.WispTask$CacheableCoroutine', 'nativeMethod': False}, {'methodName': 'startInternal', 'fileName': 'CoroutineBase.java', 'lineNumber': 62, 'className': 'java.dyn.CoroutineBase', 'nativeMethod': False}], 'message': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 10216882,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'localizedMessage': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 10216882,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'suppressed': []}, 'reqID': 'app_ios_TpnVj8fA19rbyzXmtEvDFl24BwUJes'}}
Traceback (most recent call last):
  File "/app/xiaomusic/xiaomusic.py", line 1151, in play_one_url
    ret = await self.xiaomusic.mina_service.play_by_url(device_id, url)
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 123, in play_by_url
    return await self.play_by_music_url(deviceId, url, _type)
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 174, in play_by_music_url
    return await self.ubus_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 59, in ubus_request
    result = await self.mina_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 49, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 100, 'message': 'ubus server internal error', 'data': {'msg': {'cause': None, 'stackTrace': [{'methodName': 'lambda$secureRelayV2$9', 'fileName': 'UbusSecurityUtils.java', 'lineNumber': 447, 'className': 'com.xiaomi.mico.common.util.UbusSecurityUtils', 'nativeMethod': False}, {'methodName': 'onSuccess', 'fileName': 'CallbackFuture.java', 'lineNumber': 34, 'className': 'com.facebook.swift.service.CallbackFuture$1', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Futures.java', 'lineNumber': 1132, 'className': 'com.google.common.util.concurrent.Futures$4', 'nativeMethod': False}, {'methodName': 'executeListener', 'fileName': 'AbstractFuture.java', 'lineNumber': 900, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'complete', 'fileName': 'AbstractFuture.java', 'lineNumber': 811, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'AbstractFuture.java', 'lineNumber': 653, 'className': 'com.google.common.util.concurrent.AbstractFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'CallbackFuture.java', 'lineNumber': 23, 'className': 'com.facebook.swift.service.CallbackFuture', 'nativeMethod': False}, {'methodName': 'set', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 401, 'className': 'com.facebook.swift.service.ThriftMethodHandler$AsyncMethodCallFuture', 'nativeMethod': False}, {'methodName': 'onResponseReceived', 'fileName': 'ThriftMethodHandler.java', 'lineNumber': 244, 'className': 'com.facebook.swift.service.ThriftMethodHandler$1', 'nativeMethod': False}, {'methodName': 'fireResponseReceivedCallback', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 400, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'access$200', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 45, 'className': 'com.facebook.nifty.client.AbstractClientChannel', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'AbstractClientChannel.java', 'lineNumber': 346, 'className': 'com.facebook.nifty.client.AbstractClientChannel$3', 'nativeMethod': False}, {'methodName': 'runWorker', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 1149, 'className': 'java.util.concurrent.ThreadPoolExecutor', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'ThreadPoolExecutor.java', 'lineNumber': 624, 'className': 'java.util.concurrent.ThreadPoolExecutor$Worker', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'Thread.java', 'lineNumber': 853, 'className': 'java.lang.Thread', 'nativeMethod': False}, {'methodName': 'runOutsideWisp', 'fileName': 'WispTask.java', 'lineNumber': 299, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'runCommand', 'fileName': 'WispTask.java', 'lineNumber': 274, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'access$100', 'fileName': 'WispTask.java', 'lineNumber': 53, 'className': 'com.alibaba.wisp.engine.WispTask', 'nativeMethod': False}, {'methodName': 'run', 'fileName': 'WispTask.java', 'lineNumber': 241, 'className': 'com.alibaba.wisp.engine.WispTask$CacheableCoroutine', 'nativeMethod': False}, {'methodName': 'startInternal', 'fileName': 'CoroutineBase.java', 'lineNumber': 62, 'className': 'java.dyn.CoroutineBase', 'nativeMethod': False}], 'message': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 10216882,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'localizedMessage': 'rtos-rom returns null:{\n  "code": -2,\n  "exe_time": 0,\n  "ot_cost": 0,\n  "id": 10216882,\n  "error": {\n    "code": -2,\n    "message": "device offline"\n  },\n  "message": "device offline",\n  "net_cost": 0\n}', 'suppressed': []}, 'reqID': 'app_ios_TpnVj8fA19rbyzXmtEvDFl24BwUJes'}}
[18:33:26] [0.3.27] [INFO] xiaomusic.py:1137: group_player_play http://192.168.0.101:8090/music/download/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E8%8B%B1%E6%96%87%E6%AD%8CTOP100/Lou%20Bega%20-%20Angelina.wav ['b0f386b4-d47a-4d67-83b3-f82b2a708b9b'] [None]
[18:33:26] [0.3.27] [INFO] xiaomusic.py:949: 播放 Lou Bega - Angelina 失败

**Comment by lh0602** [comment]
自家音箱抽风了 重启下就好了。。。

**Comment by hanxi** [comment]
重新配置一遍吧，应该是触发风控了。
