### ISSUE TITLE
docker 用默认配置拉取运行报错

### ISSUE THREAD

**Issue by zichenw** [hanxi/xiaomusic#206]
```
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 7, in <module>
    import uvicorn
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 7, in <module>
    import uvicorn
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 7, in <module>
    import uvicorn
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 7, in <module>
    import uvicorn
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 7, in <module>
    import uvicorn
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
```
启动后无法访问端口，看日志输出一堆错误

设备 玩客云 
系统 Armbian 20.11 Buster with Linux 5.9.0-rc7-aml-s812 
docker版本 Docker version 26.1.4, build 5650f9b

**Comment by hanxi** [comment]
能否给出完整日志？是最新版本吗？

**Comment by zichenw** [comment]
> 能否给出完整日志？是最新版本吗？
搜了下，有可能是平台原因？玩客云是ARM 32位 的 https://github.com/python/cpython/issues/90118

拉取日志
```
docker run -p 8090:8090 -v /xiaomusic/music:/app/music -v /xiaomusic/conf:/app/conf hanxi/xiaomusic
root@arm:~# docker run -p 8090:8090 -v /xiaomusic/music:/app/music -v /xiaomusic/conf:/app/conf hanxi/xiaomusic
Unable to find image 'hanxi/xiaomusic:latest' locally
latest: Pulling from hanxi/xiaomusic
670631d7a00e: Pull complete
3d91208d5b77: Pull complete
356a4c7e950c: Pull complete
db2ddfa8cb26: Pull complete
d3e4c16ad91a: Pull complete
bacd033d18a8: Pull complete
f6dfd7733c66: Pull complete
a27de99ffcd9: Pull complete
46cd26145728: Pull complete
c71a6c76ad06: Pull complete
Digest: sha256:2d5f1f07f7afd97ca6c8141ff56dc7ec4b4d5fa45fcc29b4af66a66f4a66b087
Status: Downloaded newer image for hanxi/xiaomusic:latest
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 2, in <module>
    from xiaomusic.cli import main
  File "/app/xiaomusic/cli.py", line 7, in <module>
    import uvicorn
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 3, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
```

**Comment by hanxi** [comment]
docker run -p 8090:8090 -v /xiaomusic/music:/app/music -v /xiaomusic/conf:/app/conf hanxi/xiaomusic:0.2.0

**Comment by zichenw** [comment]
> docker run -p 8090:8090 -v /xiaomusic/music:/app/music -v /xiaomusic/conf:/app/conf hanxi/xiaomusic:v0.2.0

我拆机重刷了新的armbian24.5版本正常启动
