### ISSUE TITLE
Execption 'MiNAService' object has no attribute XXX

### ISSUE THREAD

**Issue by Blues-star** [hanxi/xiaomusic#208]
```log
uestId":"0b985dd227ab3a3a3b5a4e795e0712ad"}],"nextEndTime":1727345424651}'}
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1277: 开始播放下一首
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1288: _play_next. name:群青, cur_music:群青
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1241: play. search_key: name:群青
[01:31:06] [0.3.37] [INFO] xiaomusic.py:844: 根据【群青】找到歌曲【['群青']】
[01:31:06] [0.3.37] [DEBUG] xiaomusic.py:1258: 当前播放列表为：['群青']
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1353: cur_music 群青
[01:31:06] [0.3.37] [INFO] xiaomusic.py:376: try get_filename. filename:C:\\Users\\46983\\Music\\download\群青.mp3
[01:31:06] [0.3.37] [INFO] xiaomusic.py:482: get_music_url local music. name:群青, filename:/download/群青.mp3
[01:31:06] [0.3.37] [INFO] xiaomusic.py:407: get_music_sec_url. name:群青 url:http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3
[01:31:06] [0.3.37] [INFO] xiaomusic.py:376: try get_filename. filename:C:\\Users\\46983\\Music\\download\群青.mp3
[01:31:06] [0.3.37] [INFO] xiaomusic.py:421: get_music_sec_url. name:群青 filename:C:\\Users\\46983\\Music\\download\群 青.mp3
[01:31:06] [0.3.37] [INFO] xiaomusic.py:426: 本地歌曲 群青 : C:\\Users\\46983\\Music\\download\群青.mp3 http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3 的时长 362 秒
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1716: group_force_stop_xiaoai ['cfbc6038-eaf4-4555-a1b5-3253d813631c']
[01:31:06] [0.3.37] [ERROR] xiaomusic.py:1402: Execption 'MiNAService' object has no attribute 'player_pause'
Traceback (most recent call last):
  File "C:\github_repo\xiaomusic\xiaomusic\xiaomusic.py", line 1396, in force_stop_xiaoai
    ret = await self.xiaomusic.mina_service.player_pause(device_id)
AttributeError: 'MiNAService' object has no attribute 'player_pause'
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1719: group_force_stop_xiaoai ['cfbc6038-eaf4-4555-a1b5-3253d813631c'] [None]
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1356: 播放 http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3
[01:31:06] [0.3.37] [DEBUG] xiaomusic.py:1635: _get_audio_id. name: 群青 songId:687822286404715073
[01:31:06] [0.3.37] [ERROR] xiaomusic.py:1610: Execption 'MiNAService' object has no attribute 'play_by_music_url'
Traceback (most recent call last):
  File "C:\github_repo\xiaomusic\xiaomusic\xiaomusic.py", line 1598, in play_one_url
    ret = await self.xiaomusic.mina_service.play_by_music_url(
AttributeError: 'MiNAService' object has no attribute 'play_by_music_url'
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1583: group_player_play http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3 ['cfbc6038-eaf4-4555-a1b5-3253d813631c'] [None]
[01:31:06] [0.3.37] [INFO] xiaomusic.py:1359: 播放 群青 失败
[01:31:07] [0.3.37] [DEBUG] xiaomusic.py:207: Listening new message, timestamp: {'663144397': 1727371033992}
[01:31:07] [0.3.37] [DEBUG] xiaomusic.py:355: _get_last_query device_id:cfbc6038-eaf4-4555-a1b5-3253d813631c did:663144397 data:{'code': 0, 'message': 'Success', 'data': '{"bitSet":[0,1,1],"records":[{"bitSet":[0,1,1,1,1],"answers":[{"bitSet":[0,1,0,1],"type":"TTS","tts":{"bitSet":[0,1],"text":"没有发现可以操作的落地灯，先去米家绑定设备吧。"}}],"time":1727352914475,"query":"打开关闭落地灯","requestId":"526aca3c12aa40f890c265537892be76"},{"bitSet":[0,1,1,1,1],"answers":[{"bitSet":[0,1,0,1],"type":"TTS","tts":{"bitSet":[0,1],"text":"没问题，开啦。"}}],"time":1727352895903,"query":"OPEN空调","requestId":"0b985dd227ab3a3a3b5a4e795e0712ad"}],"nextEndTime":1727345424651}'}
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1277: 开始播放下一首
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1288: _play_next. name:群青, cur_music:群青
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1241: play. search_key: name:群青
[01:31:07] [0.3.37] [INFO] xiaomusic.py:844: 根据【群青】找到歌曲【['群青']】
[01:31:07] [0.3.37] [DEBUG] xiaomusic.py:1258: 当前播放列表为：['群青']
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1353: cur_music 群青
[01:31:07] [0.3.37] [INFO] xiaomusic.py:376: try get_filename. filename:C:\\Users\\46983\\Music\\download\群青.mp3
[01:31:07] [0.3.37] [INFO] xiaomusic.py:482: get_music_url local music. name:群青, filename:/download/群青.mp3
[01:31:07] [0.3.37] [INFO] xiaomusic.py:407: get_music_sec_url. name:群青 url:http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3
[01:31:07] [0.3.37] [INFO] xiaomusic.py:376: try get_filename. filename:C:\\Users\\46983\\Music\\download\群青.mp3
[01:31:07] [0.3.37] [INFO] xiaomusic.py:421: get_music_sec_url. name:群青 filename:C:\\Users\\46983\\Music\\download\群 青.mp3
[01:31:07] [0.3.37] [INFO] xiaomusic.py:426: 本地歌曲 群青 : C:\\Users\\46983\\Music\\download\群青.mp3 http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3 的时长 362 秒
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1716: group_force_stop_xiaoai ['cfbc6038-eaf4-4555-a1b5-3253d813631c']
[01:31:07] [0.3.37] [ERROR] xiaomusic.py:1402: Execption 'MiNAService' object has no attribute 'player_pause'
Traceback (most recent call last):
  File "C:\github_repo\xiaomusic\xiaomusic\xiaomusic.py", line 1396, in force_stop_xiaoai
    ret = await self.xiaomusic.mina_service.player_pause(device_id)
AttributeError: 'MiNAService' object has no attribute 'player_pause'
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1719: group_force_stop_xiaoai ['cfbc6038-eaf4-4555-a1b5-3253d813631c'] [None]
[01:31:07] [0.3.37] [INFO] xiaomusic.py:1356: 播放 http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3
[01:31:08] [0.3.37] [DEBUG] xiaomusic.py:1635: _get_audio_id. name: 群青 songId:687822286404715073
[01:31:08] [0.3.37] [ERROR] xiaomusic.py:1610: Execption 'MiNAService' object has no attribute 'play_by_music_url'
Traceback (most recent call last):
  File "C:\github_repo\xiaomusic\xiaomusic\xiaomusic.py", line 1598, in play_one_url
    ret = await self.xiaomusic.mina_service.play_by_music_url(
AttributeError: 'MiNAService' object has no attribute 'play_by_music_url'
[01:31:08] [0.3.37] [INFO] xiaomusic.py:1583: group_player_play http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3 ['cfbc6038-eaf4-4555-a1b5-3253d813631c'] [None]
[01:31:08] [0.3.37] [INFO] xiaomusic.py:1359: 播放 群青 失败
[01:31:08] [0.3.37] [DEBUG] xiaomusic.py:207: Listening new message, timestamp: {'663144397': 1727371033992}
[01:31:08] [0.3.37] [DEBUG] xiaomusic.py:355: _get_last_query device_id:cfbc6038-eaf4-4555-a1b5-3253d813631c did:663144397 data:{'code': 0, 'message': 'Success', 'data': '{"bitSet":[0,1,1],"records":[{"bitSet":[0,1,1,1,1],"answers":[{"bitSet":[0,1,0,1],"type":"TTS","tts":{"bitSet":[0,1],"text":"没有发现可以操作的落地灯，先去米家绑定设备吧。"}}],"time":1727352914475,"query":"打开关闭落地灯","requestId":"526aca3c12aa40f890c265537892be76"},{"bitSet":[0,1,1,1,1],"answers":[{"bitSet":[0,1,0,1],"type":"TTS","tts":{"bitSet":[0,1],"text":"没问题，开啦。"}}],"time":1727352895903,"query":"OPEN空调","requestId":"0b985dd227ab3a3a3b5a4e795e0712ad"}],"nextEndTime":1727345424651}'}
[01:31:08] [0.3.37] [DEBUG] xiaomusic.py:1042: playingmusic. cur_music:群青
[01:31:08] [0.3.37] [INFO] 127.0.0.1:55610 - "GET /playingmusic?did=663144397 HTTP/1.1" 200
[01:31:09] [0.3.37] [INFO] xiaomusic.py:1277: 开始播放下一首
[01:31:09] [0.3.37] [INFO] xiaomusic.py:1288: _play_next. name:群青, cur_music:群青
[01:31:09] [0.3.37] [INFO] xiaomusic.py:1241: play. search_key: name:群青
[01:31:09] [0.3.37] [INFO] xiaomusic.py:844: 根据【群青】找到歌曲【['群青']】
[01:31:09] [0.3.37] [DEBUG] xiaomusic.py:1258: 当前播放列表为：['群青']
[01:31:09] [0.3.37] [INFO] xiaomusic.py:1353: cur_music 群青
[01:31:09] [0.3.37] [INFO] xiaomusic.py:376: try get_filename. filename:C:\\Users\\46983\\Music\\download\群青.mp3
[01:31:09] [0.3.37] [INFO] xiaomusic.py:482: get_music_url local music. name:群青, filename:/download/群青.mp3
[01:31:09] [0.3.37] [INFO] xiaomusic.py:407: get_music_sec_url. name:群青 url:http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3
[01:31:09] [0.3.37] [INFO] xiaomusic.py:376: try get_filename. filename:C:\\Users\\46983\\Music\\download\群青.mp3
[01:31:09] [0.3.37] [INFO] xiaomusic.py:421: get_music_sec_url. name:群青 filename:C:\\Users\\46983\\Music\\download\群 青.mp3
[01:31:09] [0.3.37] [INFO] xiaomusic.py:426: 本地歌曲 群青 : C:\\Users\\46983\\Music\\download\群青.mp3 http://192.168.66.116:38080/music//download/%E7%BE%A4%E9%9D%92.mp3 的时长 362 秒
[01:31:09] [0.3.37] [INFO] xiaomusic.py:1716: group_force_stop_xiaoai ['cfbc6038-eaf4-4555-a1b5-3253d813631c']
[01:31:09] [0.3.37] [ERROR] xiaomusic.py:1402: Execption 'MiNAService' object has no attribute 'player_pause'
```

新版本一直出现这个问题导致无法播放，歌曲下载什么的都是正常的，但是小爱什么的都控制不了

**Comment by hanxi** [comment]
依赖库版本问题，你是怎么安装的呢？

**Comment by 7zzz-t** [comment]
miservice_fork 版本问题
