### ISSUE TITLE
docker容器报错

### ISSUE THREAD

**Issue by Q3B0** [hanxi/xiaomusic#244]
```
Traceback (most recent call last):

  File "/app/xiaomusic.py", line 2, in <module>

    from xiaomusic.cli import main

  File "/app/xiaomusic/cli.py", line 10, in <module>

    from xiaomusic.config import Config

  File "/app/xiaomusic/config.py", line 9, in <module>

    from xiaomusic.utils import validate_proxy

  File "/app/xiaomusic/utils.py", line 37, in <module>

    from PIL import Image

  File "/app/.venv/lib/python3.10/site-packages/PIL/Image.py", line 97, in <module>

    from . import _imaging as core

ImportError: libtiff.so.6: cannot open shared object file: No such file or directory
```

**Comment by Q3B0** [comment]
0.2.0可以用
