### ISSUE TITLE
0.3.47还正常，升到0.3.48就用不了 了

### ISSUE THREAD

**Issue by zuoyou123678** [hanxi/xiaomusic#271]
日子太大了.几十兆了，我复制了部分，麻烦懂得人，百忙中稍微看下，是不是我哪里弄错了.谢谢

stderr:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
stderr: socket.gaierror: [Errno -3] Temporary failure in name resolution
stderr: 
stderr: The above exception was the direct cause of the following exception:
stderr: 
stderr: Traceback (most recent call last):
stderr:   File "/app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
stderr:     result = await app(  # type: ignore[func-returns-value]
stderr:   File "/app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
stderr:     return await self.app(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
stderr:     await super().__call__(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
stderr:     await self.middleware_stack(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
stderr:     raise exc
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
stderr:     await self.app(scope, receive, _send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
stderr:     await self.app(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
stderr:     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
stderr:     raise exc
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
stderr:     await app(scope, receive, sender)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
stderr:     await self.middleware_stack(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
stderr:     await route.handle(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
stderr:     await self.app(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
stderr:     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
stderr:     raise exc
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
stderr:     await app(scope, receive, sender)
stderr:   File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
stderr:     response = await f(request)
stderr:   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
stderr:     raw_response = await run_endpoint_function(
stderr:   File "/app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
stderr:     return await dependant.call(**values)
stderr:   File "/app/xiaomusic/httpserver.py", line 406, in latest_version
stderr:     version = await get_latest_version("xiaomusic")
stderr:   File "/app/xiaomusic/utils.py", line 554, in get_latest_version
stderr:     async with session.get(url) as response:
stderr:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1418, in __aenter__
stderr:     self._resp: _RetType = await self._coro
stderr:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 696, in _request
stderr:     conn = await self._connector.connect(
stderr:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
stderr:     proto = await self._create_connection(req, traces, timeout)
stderr:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1050, in _create_connection
stderr:     _, proto = await self._create_direct_connection(req, traces, timeout)
stderr:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
stderr:     raise ClientConnectorDNSError(req.connection_key, exc) from exc
stderr: aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host pypi.org:443 ssl:default [Temporary failure in name resolution]
stderr: [2024-11-23 12:34:12] [0.3.48] [INFO] ga4mp.py:183: Sending POST to: https://www.google-analytics.com/mp/collect
stderr: [2024-11-23 12:34:15] [0.3.48] [INFO] ga4mp.py:223: Batch Number: 1
stderr: [2024-11-23 12:34:15] [0.3.48] [INFO] ga4mp.py:224: Status code: 204
stdout: [12:39:18] [0.3.48] [INFO] 172.18.0.1:43286 - "GET / HTTP/1.1" 200
stdout: [12:39:18] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /static/xiaoai.png HTTP/1.1" 200
stdout: [12:39:20] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /static/default/index.html HTTP/1.1" 200
stdout: [12:39:20] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /static/default/jquery-3.7.1.min.js?version=1732033916 HTTP/1.1" 200
stdout: [12:39:20] [0.3.48] [INFO] 172.18.0.1:33788 - "GET /static/default/style.css?version=1732033916 HTTP/1.1" 200
stdout: [12:39:20] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /static/default/app.js?version=1732033916 HTTP/1.1" 200
stdout: [12:39:20] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /getsetting HTTP/1.1" 200
stdout: [12:39:20] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /getversion HTTP/1.1" 200
stdout: [12:39:21] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /musiclist HTTP/1.1" 200
stdout: [12:39:21] [0.3.48] [INFO] 172.18.0.1:33788 - "GET /getvolume?did= HTTP/1.1" 200
stdout: [12:39:21] [0.3.48] [INFO] 172.18.0.1:33788 - "GET /curplaylist?did= HTTP/1.1" 200
stdout: [12:39:21] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:22] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /latestversion HTTP/1.1" 200
stdout: [12:39:22] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /favicon.ico HTTP/1.1" 404
stdout: [12:39:22] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /static/favicon.ico HTTP/1.1" 200
stdout: [12:39:24] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /playingmusic?did= HTTP/1.1" 200
stderr: [2024-11-23 12:39:26] [0.3.48] [INFO] httpserver.py:212: docmd. did: cmd:关机
stdout: [12:39:26] [0.3.48] [INFO] 172.18.0.1:33802 - "POST /cmd HTTP/1.1" 200
stderr: [2024-11-23 12:39:26] [0.3.48] [INFO] httpserver.py:212: docmd. did: cmd:刷新列表
stdout: [12:39:26] [0.3.48] [INFO] 172.18.0.1:33802 - "POST /cmd HTTP/1.1" 200
stdout: [12:39:26] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /cmdstatus HTTP/1.1" 200
stdout: [12:39:27] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /musiclist HTTP/1.1" 200
stdout: [12:39:27] [0.3.48] [INFO] 172.18.0.1:33802 - "GET /curplaylist?did= HTTP/1.1" 200
stdout: [12:39:27] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:27] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:30] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:30] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:33] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:33] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:36] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:36] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:39] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:39] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:42] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:42] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:45] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:45] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200
stdout: [12:39:48] [0.3.48] [INFO] 172.18.0.1:43286 - "GET /playingmusic?did= HTTP/1.1" 200

**Comment by hanxi** [comment]
试试host模式？

**Comment by hanxi** [comment]
这么明显的登陆失败啊，按照FAQ里的办法解决就可以了。

**Comment by 603711936** [comment]
谢谢 改成 host 好了😁.
