### ISSUE TITLE
无法获取小爱音箱列表

### ISSUE THREAD

**Issue by chinattw** [hanxi/xiaomusic#311]
<img width="889" alt="image" src="https://github.com/user-attachments/assets/41bf4ca7-a3ae-4a3f-9336-c86b471443f5" />
正确在xiaomusic配置了小米id和密码
<img width="643" alt="image" src="https://github.com/user-attachments/assets/d22e898e-e859-4ba0-aa5e-dd084b120170" />
正确登录了小米后台
<img width="309" alt="image" src="https://github.com/user-attachments/assets/ec5f1329-24ac-4666-8b4e-47b7a3fbb016" />
小米帐号下有绑定音箱(两个型号一样的PLAY增强版)

但在小米的后台，没有找到哪个页面可以看绑定的音箱，xiaomusic也获取不到音箱列表。

确认在xiaomusic中配置的密码没问题

<img width="707" alt="image" src="https://github.com/user-attachments/assets/926b0c98-2ab0-447b-a2f5-4025289d22cb" />

**Comment by hanxi** [comment]
什么版本？

**Comment by chinattw** [comment]
通过DOCKER的方式部署，试过0.3.57和0.3.55两个版本。均是一样的现象。
现在通过播放列表，可以播放音乐到“本地”，但无法播放到小爱音箱。

看docker后台，确实有访问https://api2.mina.mi.com/admin/v2/device_list的异常日志。
完整日志如下：
[2024-12-15 11:33:58] [0.3.55] [ERROR] miaccount.py:86: Exception on login 2854164146: Cannot connect to host account.xiaomi.com:443 ssl:False [Temporary failure in name resolution]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1345, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 989, in _resolve_host
    return await asyncio.shield(resolved_host_task)
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1020, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/resolver.py", line 36, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 56, in login
    resp = await self._serviceLogin(f"serviceLogin?sid={sid}&_json=true")
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 98, in _serviceLogin
    async with self.session.request(
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host account.xiaomi.com:443 ssl:False [Temporary failure in name resolution]
[2024-12-15 11:33:58] [0.3.55] [ERROR] xiaomusic.py:254: Execption Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_Xd7NTJ9oFDzuEbOvB6gZswHy5LRk24: Login failed
Traceback (most recent call last):
  File "/app/xiaomusic/xiaomusic.py", line 235, in try_update_device_id
    hardware_data = await self.mina_service.device_list()
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 54, in device_list
    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 49, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_Xd7NTJ9oFDzuEbOvB6gZswHy5LRk24: Login failed

**Comment by weguang** [comment]
问题同上，也没找到解决办法

**Comment by weguang** [comment]
[ERROR] miaccount.py:86: Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '************', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}

**Comment by hanxi** [comment]
多试几次吧，风控问题，确定xiaomusic和你浏览器在同一个局域网。

**Comment by weguang** [comment]
感谢亲自解答，排查到原因是python版本没管理好，导致老的python下载匹配到了老的包。现在mp3以及可以正常使用👍
就是 `L05B` 确实播放不了flac，跟文档相符，打开那个兼容性也不行。
最后测试了下转换为mp3，临时文件夹mp3正常生成，但音箱没声。

**Comment by jjjyyyllll** [comment]
> 多试几次吧，风控问题，确定xiaomusic和你浏览器在同一个局域网。

我这个是pure主题不行，在pure的设置里可以看得到设备，播放列表中没有设备。如图。
![QQ拼音截图20241220191825](https://github.com/user-attachments/assets/b087ade1-7a3d-4742-a31e-651fb6be3d60)
![QQ拼音截图20241220191847](https://github.com/user-attachments/assets/51c864f9-7421-4343-906b-e2e28c588637)

在默认主题里面都正常

**Comment by lihuayuyiliang** [comment]
关闭本地代理。
如果是nas运行的，网络由bridge改为host。
米家app重新登陆。
mi.com官网重新登陆。
都试过了，还是401登录失败，使用的是windows10，没开代理在同一个局域网内，app和网页都重登了

**Comment by jackiepang15** [comment]
关闭双重验证，再试一下？
