### ISSUE TITLE
小爱音箱自动播放

### ISSUE THREAD

**Issue by Sniper498350661** [hanxi/xiaomusic#342]
安装完成以后，小爱音箱偶尔抽风自行播放本地硬盘歌曲。版本号;66；

**Comment by hanxi** [comment]
确保在后台点了停止按钮。

**Comment by fjfb001** [comment]
遇到同样的问题。语音要求退出后和小程序点击停止后，均出现幽灵播放。希望大神辛苦排查。

**Comment by zxhans** [comment]
晚上睡觉还真得关闭docker，哈哈 挺吓人的

**Comment by fjfb001** [comment]
哈哈，已经关闭容器了。等大神推新版本。

**Comment by leaguetao** [comment]
卧槽  原来不是我一个这样  太恐怖了

**Comment by suhaiyou945** [comment]
我的也是这样，时不时的自己播放，太不正常了。5分钟左右。

**Comment by hanxi** [comment]
半夜关容器就正常了？

**Comment by suhaiyou945** [comment]
关闭容器，应该是可以的，期待大佬能完善，这个镜像太好了，不错的项目。

**Comment by hanxi** [comment]
具体什么型号？

**Comment by ksi1110** [comment]
一样的问题，小爱音响pro，今天播放歌曲非常奇怪，一首播放完后，切下一首会空白大概几十秒，手动切没有这个问题。并且更新0.3.76版本后巨卡顿，我还以为本地硬盘出问题了，换个机器试一样卡顿。并且语音指令退出后，一会就又自动播放了。。。只能把容器给停止了，等大佬排查更新吧😂

**Comment by suhaiyou945** [comment]
> 具体什么型号？

小米音箱pro,型号LX06

**Comment by leaguetao** [comment]
一样发自我的荣耀手机-------- 原始邮件 --------发件人： suhaiyou945 ***@***.***>日期： 2024年12月30日周一 23:19收件人： hanxi/xiaomusic ***@***.***>抄送： 湖北张小七 ***@***.***>, Comment ***@***.***>主    题： Re: [hanxi/xiaomusic] 小爱音箱自动播放 (Issue #342)

具体什么型号？

小米音箱pro,型号LX06

**Comment by zhecydn** [comment]
小爱同学play增强版也碰到这个问题了

**Comment by miaomiaoguoke** [comment]
小爱触屏音箱Pro8同样的问题，暂停后一会儿就自动开始了。

**Comment by hanxi** [comment]
> 小爱触屏音箱Pro8同样的问题，暂停后一会儿就自动开始了。

怎么操作的暂停呢？如果是屏幕上操作的，是这样的，需要语音口令停止，或者网页后台点停止。

**Comment by alexyangtao** [comment]
一样的问题，小米 AI 音箱	S12
以下是日志：

stdout: [2025-01-02 15:14:42] [0.3.68] [INFO] xiaomusic.py:1943: 定时器时间到了
stdout: [2025-01-02 15:14:42] [0.3.68] [INFO] xiaomusic.py:1519: 开始播放下一首
stdout: [2025-01-02 15:14:42] [0.3.68] [INFO] xiaomusic.py:417: try get_filename. filename:music/Alex/王闻 - 再见二丁目.mp3
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:1531: _play_next. name:王闻 - 再见二丁目, cur_music:M2M - Pretty Boy
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:1480: play. search_key: name:王闻 - 再见二丁目
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:943: 根据【王闻 - 再见二丁目】找到歌曲【['王闻 - 再见二丁目']】
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:2040: cancel_group_next_timer {'114746315': <xiaomusic.xiaomusic.XiaoMusicDevice object at 0xffff9a2aa3b0>}
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:2030: cancel_next_timer
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:2036: 下一曲定时器不见了
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:1604: cur_music 王闻 - 再见二丁目
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:417: try get_filename. filename:music/Alex/王闻 - 再见二丁目.mp3
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:527: get_music_url local music. name:王闻 - 再见二丁目, filename:Alex/王闻 - 再见二丁目.mp3
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:448: get_music_sec_url. name:王闻 - 再见二丁目 url:http://192.168.50.154:8090/music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:417: try get_filename. filename:music/Alex/王闻 - 再见二丁目.mp3
stdout: [2025-01-02 15:14:43] [0.3.68] [INFO] xiaomusic.py:462: get_music_sec_url. name:王闻 - 再见二丁目 filename:music/Alex/王闻 - 再见二丁目.mp3
stdout: [2025-01-02 15:14:45] [0.3.68] [INFO] xiaomusic.py:467: 本地歌曲 王闻 - 再见二丁目 : music/Alex/王闻 - 再见二丁目.mp3 http://192.168.50.154:8090/music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a 的时长 239 秒
stdout: [2025-01-02 15:14:45] [0.3.68] [INFO] xiaomusic.py:2007: group_force_stop_xiaoai ['0eca3be1-9743-4d06-9a16-216f27d5a196']
stdout: [2025-01-02 15:14:45] [0.3.68] [INFO] xiaomusic.py:1659: force_stop_xiaoai player_pause device_id:0eca3be1-9743-4d06-9a16-216f27d5a196 ret:{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}
stdout: [2025-01-02 15:14:46] [0.3.68] [INFO] xiaomusic.py:1670: {'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0, 'info': '{ "status": 1, "volume": 28, "loop_type": 2 }'}}
stdout: [2025-01-02 15:14:47] [0.3.68] [INFO] xiaomusic.py:1683: stop_if_xiaoai_is_playing player_stop device_id:0eca3be1-9743-4d06-9a16-216f27d5a196 enable_force_stop:False ret:{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}
stdout: [2025-01-02 15:14:47] [0.3.68] [INFO] xiaomusic.py:2010: group_force_stop_xiaoai ['0eca3be1-9743-4d06-9a16-216f27d5a196'] [None]
stdout: [2025-01-02 15:14:47] [0.3.68] [INFO] xiaomusic.py:1607: 播放 http://192.168.50.154:8090/music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a
stdout: [15:14:47] [0.3.68] [INFO] 172.17.0.1:36744 - "GET /music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a HTTP/1.1" 206
stdout: [2025-01-02 15:14:47] [0.3.68] [INFO] xiaomusic.py:1889: play_one_url play_by_url device_id:0eca3be1-9743-4d06-9a16-216f27d5a196 ret:{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}} url:http://192.168.50.154:8090/music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a
stdout: [2025-01-02 15:14:47] [0.3.68] [INFO] xiaomusic.py:1864: group_player_play http://192.168.50.154:8090/music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a ['0eca3be1-9743-4d06-9a16-216f27d5a196'] [{'code': 0, 'message': "Msg has been successfully proxy to the device, this service is a simple proxy, if you encounter any problems pls contact ROM's developers directly!!!", 'data': {'code': 0}}]
stdout: [2025-01-02 15:14:47] [0.3.68] [INFO] xiaomusic.py:1623: 【王闻 - 再见二丁目】已经开始播放了
stdout: [15:14:47] [0.3.68] [INFO] 172.17.0.1:36756 - "GET /music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a HTTP/1.1" 206
stdout: [15:14:47] [0.3.68] [INFO] 172.17.0.1:36766 - "GET /music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a HTTP/1.1" 206
stdout: [15:14:47] [0.3.68] [INFO] 172.17.0.1:36782 - "GET /music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a HTTP/1.1" 206
stdout: [15:14:47] [0.3.68] [INFO] 172.17.0.1:36794 - "GET /music/Alex/%E7%8E%8B%E9%97%BB%20-%20%E5%86%8D%E8%A7%81%E4%BA%8C%E4%B8%81%E7%9B%AE.mp3?code=393d69e5177d5c420ffe65c0caea4d0f156970255e9eddbd8cf90a2c005dbd8a HTTP/1.1" 206
stdout: [15:15:02] [0.3.68] [INFO] 172.17.0.1:41258 - "GET /playingmusic?did=114746315 HTTP/1.1" 200
stdout: [15:16:01] [0.3.68] [INFO] 172.17.0.1:40726 - "GET /playingmusic?did=114746315 HTTP/1.1" 200
stdout: [15:17:02] [0.3.68] [INFO] 172.17.0.1:43516 - "GET /playingmusic?did=114746315 HTTP/1.1" 200
stdout: [15:18:01] [0.3.68] [INFO] 172.17.0.1:57600 - "GET /playingmusic?did=114746315 HTTP/1.1" 200
stdout: [2025-01-02 15:18:23] [0.3.68] [ERROR] analytics.py:108: Execption Connection timeout to host https://umami.hanxi.cc/api/send
stdout: Traceback (most recent call last):
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1115, in _wrap_create_connection
stdout:     sock = await aiohappyeyeballs.start_connection(
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
stdout:     sock = await _connect_sock(
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
stdout:     await loop.sock_connect(sock, address)
stdout:   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
stdout:     return await fut
stdout: asyncio.exceptions.CancelledError
stdout: 
stdout: During handling of the above exception, another exception occurred:
stdout: 
stdout: Traceback (most recent call last):
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 703, in _request
stdout:     conn = await self._connector.connect(
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 548, in connect
stdout:     proto = await self._create_connection(req, traces, timeout)
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1056, in _create_connection
stdout:     _, proto = await self._create_direct_connection(req, traces, timeout)
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1400, in _create_direct_connection
stdout:     raise last_exc
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1369, in _create_direct_connection
stdout:     transp, proto = await self._wrap_create_connection(
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1112, in _wrap_create_connection
stdout:     async with ceil_timeout(
stdout:   File "/app/.venv/lib/python3.10/site-packages/async_timeout/__init__.py", line 179, in __aexit__
stdout:     self._do_exit(exc_type)
stdout:   File "/app/.venv/lib/python3.10/site-packages/async_timeout/__init__.py", line 265, in _do_exit
stdout:     raise asyncio.TimeoutError
stdout: asyncio.exceptions.TimeoutError
stdout: 
stdout: The above exception was the direct cause of the following exception:
stdout: 
stdout: Traceback (most recent call last):
stdout:   File "/app/xiaomusic/analytics.py", line 104, in post_to_umami
stdout:     async with session.post(url, json=data, headers=headers) as response:
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1425, in __aenter__
stdout:     self._resp: _RetType = await self._coro
stdout:   File "/app/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 707, in _request
stdout:     raise ConnectionTimeoutError(
stdout: aiohttp.client_exceptions.ConnectionTimeoutError: Connection timeout to host https://umami.hanxi.cc/api/send
stdout: [2025-01-02 15:18:23] [0.3.68] [INFO] analytics.py:73: analytics run_with_cancel success
stdout: [2025-01-02 15:18:23] [0.3.68] [INFO] xiaomusic.py:2030: cancel_next_timer
stdout: [2025-01-02 15:18:23] [0.3.68] [INFO] xiaomusic.py:2036: 下一曲定时器不见了
stdout: [2025-01-02 15:18:23] [0.3.68] [INFO] xiaomusic.py:1954: 239 秒后将会播放下一首歌曲
stdout: [2025-01-02 15:18:23] [0.3.68] [INFO] xiaomusic.py:1321: save_cur_config ok
stdout: [15:19:02] [0.3.68] [INFO] 172.17.0.1:46264 - "GET /playingmusic?did=114746315 HTTP/1.1" 200

**Comment by hanxi** [comment]
升级69版本试试吧

**Comment by suhaiyou945** [comment]
> 升级69版本试试吧

升级后，完美解决了，太好了，老大给你点赞！
