### ISSUE TITLE
无法安装 

### ISSUE THREAD

**Issue by hbhqqq** [hanxi/xiaomusic#61]
2024-05-17 22:00:24 Traceback (most recent call last):
2024-05-17 22:00:24   File "/app/xiaomusic.py", line 5, in <module>
2024-05-17 22:00:24     main()
2024-05-17 22:00:24   File "/app/xiaomusic/cli.py", line 67, in main
2024-05-17 22:00:24     loop.run_until_complete(xiaomusic.run_forever())
2024-05-17 22:00:24   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-05-17 22:00:24     return future.result()
2024-05-17 22:00:24   File "/app/xiaomusic/xiaomusic.py", line 416, in run_forever
2024-05-17 22:00:24     await self.init_all_data(session)
2024-05-17 22:00:24   File "/app/xiaomusic/xiaomusic.py", line 110, in init_all_data
2024-05-17 22:00:24     await self._init_data_hardware()
2024-05-17 22:00:24   File "/app/xiaomusic/xiaomusic.py", line 148, in _init_data_hardware
2024-05-17 22:00:24     raise Exception(
2024-05-17 22:00:24 Exception: we have no hardware: LX05A please use `micli mina` to check

**Comment by hanxi** [comment]
你的设备类型是不是写错了？类型应该不是 LX05A

**Comment by hbhqqq** [comment]
DiD 搞不定 容器一直重启

**Comment by hbhqqq** [comment]
> 你的设备类型是不是写错了？类型应该不是 LX05A

小爱音箱万能遥控板。音箱底下 显示型号为LX05A
