### ISSUE TITLE
使用基础设置，启动失败

### ISSUE THREAD

**Issue by weiyideai520** [hanxi/xiaomusic#67]
[08:25:19] INFO     [0.1.34]        The file music/setting.json xiaomusic.py:620
                    does not exist.                                             
[08:25:20] INFO     [0.1.34]        Serving on 0.0.0.0:8090    httpserver.py:122
Traceback (most recent call last):
  File "/app/xiaomusic/xiaomusic.py", line 169, in _init_data_hardware
    self.config.mi_did = next(
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/xiaomusic.py", line 5, in <module>
    main()
  File "/app/xiaomusic/cli.py", line 67, in main
    loop.run_until_complete(xiaomusic.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaomusic/xiaomusic.py", line 426, in run_forever
    await self.init_all_data(session)
  File "/app/xiaomusic/xiaomusic.py", line 122, in init_all_data
    await self._init_data_hardware()
  File "/app/xiaomusic/xiaomusic.py", line 175, in _init_data_hardware
    raise Exception(
Exception: cannot find did for hardware: L07A please set it via MI_DID env

**Comment by weiyideai520** [comment]
> 在网页控制台页面设置下did再重启试试。



> 在网页控制台页面设置下did再重启试试。

可以了，感谢

请问一下，这个可以和 小爱音响 对话 播放音乐吗？
还是只能 网页控制它播放   ？

**Comment by hanxi** [comment]
可以语言播放，后续优化下启动失败的问题。
